library(data.table)

sf <- read.csv('symptoms_200910.csv', header=T, sep=';');
bf <- read.csv('background_200910.csv', header=T, sep=';');
cf <- read.csv('contacts_200910.csv', header=T, sep=';');
vf <- read.csv('vaccine_200910.csv', header=T, sep=';');

st <- data.table(sf)
bt <- data.table(bf)
ct <- data.table(cf)
vt <- data.table(vf)

st$date <- as.Date(st$date)
bt$date <- as.Date(bt$date)
ct$date <- as.Date(ct$date)
vt$date <- as.Date(vt$date)

setnames(bt, 1, "bid")
setnames(ct, 1, "cid")
setnames(vt, 1, "vid")

setkey(bt, uid, date)
setkey(ct, uid, date)
setkey(vt, uid, date)

st <- st[-(1:6),]

setkey(st, uid, date)
dt <- bt[vt[ct[st, roll=TRUE], roll=TRUE], roll=TRUE]

setnames(dt, 4, "postcode")
setnames(dt, 5, "birthyear")
setnames(dt, 6, "transport")
setnames(dt, 10, "vaccine.last.year")
setnames(dt, 11, "riskgroup")
setnames(dt, 12, "smoke")
setnames(dt, 15, "exercise")
setnames(dt, 17, "nb.household")
setnames(dt, 18, "nb.household.0-4")
setnames(dt, 19, "nb.household.5-18")
setnames(dt, 20, "nb.household.19-64")
setnames(dt, 21, "nb.household.65+")
setnames(dt, 22, "school.nursery")
setnames(dt, 24, "frequent.contact")
setnames(dt, 46, "chronic.heart.disease")
setnames(dt, 47, "diabetes")
setnames(dt, 48, "asthma")
setnames(dt, 49, "other.chronic.lung.disease")
setnames(dt, 50, "pregnant")
setnames(dt, 51, "immunocompromised")
setnames(dt, 52, "other.chronic")
setnames(dt, 53, "frequent.contact.children")
setnames(dt, 54, "frequent.contact.patients")
setnames(dt, 55, "frequent.contact.elderly")
setnames(dt, 56, "frequent.contact.people")
setnames(dt, 88, "offered.swineflu.vaccine")
setnames(dt, 89, "why.offered.swineflu.vaccine")
setnames(dt, 90, "had.swineflu.vaccine")
setnames(dt, 91, "intend.vaccine")
setnames(dt, 92, "date.swineflu.vaccine")
setnames(dt, 93, "why.not.swineflu.vaccine")
setnames(dt, 94, "why.swineflu.vaccine")
setnames(dt, 95, "offered.seasonal.vaccine")
setnames(dt, 96, "why.offered.seasonal.vaccine")
setnames(dt, 97, "had.seasonal.vaccine")
setnames(dt, 98, "intend.vaccine")
setnames(dt, 99, "date.seasonal.vaccine")
setnames(dt, 100, "why.not.seasonal.vaccine")
setnames(dt, 101, "why.seasonal.vaccine")
setnames(dt, 102, "why.offered.seasonal.vaccine.healthcare.worker")
setnames(dt, 103, "why.offered.seasonal.vaccine.hospital.patient")
setnames(dt, 104, "why.offered.seasonal.vaccine.underlying.health.condition")
setnames(dt, 105, "why.offered.seasonal.vaccine.pregnant")
setnames(dt, 106, "why.offered.seasonal.vaccine.close.contact.with.high.risk")
setnames(dt, 107, "why.offered.seasonal.vaccine.over.65")
setnames(dt, 108, "why.offered.seasonal.vaccine.under.5")
setnames(dt, 110, "why.offered.seasonal.vaccine.other")
setnames(dt, 111, "why.offered.seasonal.vaccine.dont.know")
setnames(dt, 112, "why.not.swineflu.vaccine.doctor")
setnames(dt, 113, "why.not.swineflu.vaccine.already")
setnames(dt, 114, "why.not.swineflu.vaccine.not.risk")
setnames(dt, 115, "why.not.swineflu.vaccine.side.effects")
setnames(dt, 116, "why.not.swineflu.vaccine.other")
setnames(dt, 117, "why.not.swineflu.vaccine.dont.know")
setnames(dt, 118, "why.swineflu.vaccine.doctor")
setnames(dt, 119, "why.swineflu.vaccine.highrisk")
setnames(dt, 120, "why.swineflu.vaccine.protected")
setnames(dt, 121, "why.swineflu.vaccine.protect.others")
setnames(dt, 122, "why.swineflu.vaccine.other")
setnames(dt, 123, "why.swineflu.vaccine.dontknow")
setnames(dt, 124, "why.offered.seasonal.vaccine.healthcare.worker")
setnames(dt, 125, "why.offered.seasonal.vaccine.hospital.patient")
setnames(dt, 126, "why.offered.seasonal.vaccine.underlying.health.condition")
setnames(dt, 127, "why.offered.seasonal.vaccine.pregnant")
setnames(dt, 128, "why.offered.seasonal.vaccine.over.65")
setnames(dt, 129, "why.offered.seasonal.vaccine.other")
setnames(dt, 130, "why.offered.seasonal.vaccine.dont.know")
setnames(dt, 131, "why.not.seasonal.vaccine.doctor")
setnames(dt, 132, "why.not.seasonal.vaccine.already")
setnames(dt, 133, "why.not.seasonal.vaccine.not.risk")
setnames(dt, 134, "why.not.seasonal.vaccine.side.effects")
setnames(dt, 135, "why.not.seasonal.vaccine.other")
setnames(dt, 136, "why.not.seasonal.vaccine.dont.know")
setnames(dt, 137, "why.seasonal.vaccine.doctor")
setnames(dt, 138, "why.seasonal.vaccine.highrisk")
setnames(dt, 139, "why.seasonal.vaccine.protected")
setnames(dt, 140, "why.seasonal.vaccine.protect.others")
setnames(dt, 141, "why.seasonal.vaccine.other")
setnames(dt, 142, "why.seasonal.vaccine.dontknow")
setnames(dt, 143, "conversational.home.0-4")
setnames(dt, 144, "conversational.home.5-18")
setnames(dt, 145, "conversational.home.19-64")
setnames(dt, 146, "conversational.home.65+")
setnames(dt, 147, "conversational.work.0-4")
setnames(dt, 148, "conversational.work.5-18")
setnames(dt, 149, "conversational.work.19-64")
setnames(dt, 150, "conversational.work.65+")
setnames(dt, 151, "conversational.other.0-4")
setnames(dt, 152, "conversational.other.5-18")
setnames(dt, 153, "conversational.other.19-64")
setnames(dt, 154, "conversational.other.65+")
setnames(dt, 155, "physical.home.0-4")
setnames(dt, 156, "physical.home.5-18")
setnames(dt, 157, "physical.home.19-64")
setnames(dt, 158, "physical.home.65+")
setnames(dt, 159, "physical.work.0-4")
setnames(dt, 160, "physical.work.5-18")
setnames(dt, 161, "physical.work.19-64")
setnames(dt, 162, "physical.work.65+")
setnames(dt, 163, "physical.other.0-4")
setnames(dt, 164, "physical.other.5-18")
setnames(dt, 165, "physical.other.19-64")
setnames(dt, 166, "physical.other.65+")
setnames(dt, 167, "public.transport")
setnames(dt, 168, "enclosed.indoor.space")
setnames(dt, 170, "symptoms")
setnames(dt, 171, "symptoms.start")
setnames(dt, 172, "fever")
setnames(dt, 173, "fever.start")
setnames(dt, 179, "alter.routine")
setnames(dt, 180, "howlong.altered")
setnames(dt, 188, "blocked.runny.nose")
setnames(dt, 189, "cough")
setnames(dt, 190, "sore.throat")
setnames(dt, 191, "headache")
setnames(dt, 192, "muscle.and.or.joint.pain")
setnames(dt, 193, "chest.pain")
setnames(dt, 194, "stomach.ache")
setnames(dt, 195, "diarrhoea")
setnames(dt, 196, "nausea")
setnames(dt, 197, "chills")
setnames(dt, 198, "weakness")
setnames(dt, 199, "eye.irritation")
setnames(dt, 200, "fever.symptom")
setnames(dt, 201, "no.symptoms")

