SET statement_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;

SET search_path = public, pg_catalog;

DROP VIEW epidb_health_status;
CREATE VIEW epidb_health_status AS
    SELECT epidb_results_weekly.id AS epidb_results_weekly_id, CASE true WHEN epidb_results_weekly."Q1_0" THEN 'NO-SYMPTOMS'::text WHEN ((((epidb_results_weekly."Q5" = 0) OR (epidb_results_weekly."Q6b" = 0)) AND (((((((epidb_results_weekly."Q1_1" OR epidb_results_weekly."Q1_2") OR (epidb_results_weekly."Q6d" = 3)) OR (epidb_results_weekly."Q6d" = 4)) OR (epidb_results_weekly."Q6d" = 5)) OR epidb_results_weekly."Q1_11") OR epidb_results_weekly."Q1_8") OR epidb_results_weekly."Q1_9")) AND ((epidb_results_weekly."Q1_5" OR epidb_results_weekly."Q1_6") OR epidb_results_weekly."Q1_7")) THEN 'ILI'::text WHEN ((((((NOT epidb_results_weekly."Q1_1") AND (NOT epidb_results_weekly."Q1_2")) AND ((epidb_results_weekly."Q6d" = 0) OR (epidb_results_weekly."Q6d" IS NULL))) AND ((epidb_results_weekly."Q1_3" OR epidb_results_weekly."Q1_4") OR epidb_results_weekly."Q1_14")) AND (epidb_results_weekly."Q11" = 2)) AND ((((CASE true WHEN epidb_results_weekly."Q1_17" THEN 1 ELSE 0 END + CASE true WHEN epidb_results_weekly."Q1_15" THEN 1 ELSE 0 END) + CASE true WHEN epidb_results_weekly."Q1_16" THEN 1 ELSE 0 END) + CASE true WHEN epidb_results_weekly."Q1_18" THEN 1 ELSE 0 END) >= 2)) THEN 'ALLERGY-or-HAY-FEVER-and-GASTROINTESTINAL'::text WHEN (((((NOT epidb_results_weekly."Q1_1") AND (NOT epidb_results_weekly."Q1_2")) AND ((epidb_results_weekly."Q6d" = 0) OR (epidb_results_weekly."Q6d" IS NULL))) AND ((epidb_results_weekly."Q1_3" OR epidb_results_weekly."Q1_4") OR epidb_results_weekly."Q1_14")) AND (epidb_results_weekly."Q11" = 2)) THEN 'ALLERGY-or-HAY-FEVER'::text WHEN (((((CASE true WHEN epidb_results_weekly."Q1_3" THEN 1 ELSE 0 END + CASE true WHEN epidb_results_weekly."Q1_4" THEN 1 ELSE 0 END) + CASE true WHEN epidb_results_weekly."Q1_6" THEN 1 ELSE 0 END) + CASE true WHEN epidb_results_weekly."Q1_5" THEN 1 ELSE 0 END) >= 2) AND ((((CASE true WHEN epidb_results_weekly."Q1_17" THEN 1 ELSE 0 END + CASE true WHEN epidb_results_weekly."Q1_15" THEN 1 ELSE 0 END) + CASE true WHEN epidb_results_weekly."Q1_16" THEN 1 ELSE 0 END) + CASE true WHEN epidb_results_weekly."Q1_18" THEN 1 ELSE 0 END) >= 2)) THEN 'COMMON-COLD-and-GASTROINTESTINAL'::text WHEN ((((CASE true WHEN epidb_results_weekly."Q1_3" THEN 1 ELSE 0 END + CASE true WHEN epidb_results_weekly."Q1_4" THEN 1 ELSE 0 END) + CASE true WHEN epidb_results_weekly."Q1_6" THEN 1 ELSE 0 END) + CASE true WHEN epidb_results_weekly."Q1_5" THEN 1 ELSE 0 END) >= 2) THEN 'COMMON-COLD'::text WHEN ((((CASE true WHEN epidb_results_weekly."Q1_17" THEN 1 ELSE 0 END + CASE true WHEN epidb_results_weekly."Q1_15" THEN 1 ELSE 0 END) + CASE true WHEN epidb_results_weekly."Q1_16" THEN 1 ELSE 0 END) + CASE true WHEN epidb_results_weekly."Q1_18" THEN 1 ELSE 0 END) >= 2) THEN 'GASTROINTESTINAL'::text ELSE 'NON-SPECIFIC-SYMPTOMS'::text END AS status FROM epidb_results_weekly;


ALTER TABLE public.epidb_health_status OWNER TO seb;


DROP VIEW epidb_health_status_notired;
CREATE VIEW epidb_health_status_notired AS
    SELECT epidb_results_weekly.id AS epidb_results_weekly_id, CASE true WHEN epidb_results_weekly."Q1_0" THEN 'NO-SYMPTOMS'::text WHEN ((((epidb_results_weekly."Q5" = 0) OR (epidb_results_weekly."Q6b" = 0)) AND ((((((epidb_results_weekly."Q1_1" OR epidb_results_weekly."Q1_2") OR (epidb_results_weekly."Q6d" = 3)) OR (epidb_results_weekly."Q6d" = 4)) OR (epidb_results_weekly."Q6d" = 5)) OR epidb_results_weekly."Q1_8") OR epidb_results_weekly."Q1_9")) AND ((epidb_results_weekly."Q1_5" OR epidb_results_weekly."Q1_6") OR epidb_results_weekly."Q1_7")) THEN 'ILI'::text WHEN ((((((NOT epidb_results_weekly."Q1_1") AND (NOT epidb_results_weekly."Q1_2")) AND ((epidb_results_weekly."Q6d" = 0) OR (epidb_results_weekly."Q6d" IS NULL))) AND ((epidb_results_weekly."Q1_3" OR epidb_results_weekly."Q1_4") OR epidb_results_weekly."Q1_14")) AND (epidb_results_weekly."Q11" = 2)) AND ((((CASE true WHEN epidb_results_weekly."Q1_17" THEN 1 ELSE 0 END + CASE true WHEN epidb_results_weekly."Q1_15" THEN 1 ELSE 0 END) + CASE true WHEN epidb_results_weekly."Q1_16" THEN 1 ELSE 0 END) + CASE true WHEN epidb_results_weekly."Q1_18" THEN 1 ELSE 0 END) >= 2)) THEN 'ALLERGY-or-HAY-FEVER-and-GASTROINTESTINAL'::text WHEN (((((NOT epidb_results_weekly."Q1_1") AND (NOT epidb_results_weekly."Q1_2")) AND ((epidb_results_weekly."Q6d" = 0) OR (epidb_results_weekly."Q6d" IS NULL))) AND ((epidb_results_weekly."Q1_3" OR epidb_results_weekly."Q1_4") OR epidb_results_weekly."Q1_14")) AND (epidb_results_weekly."Q11" = 2)) THEN 'ALLERGY-or-HAY-FEVER'::text WHEN (((((CASE true WHEN epidb_results_weekly."Q1_3" THEN 1 ELSE 0 END + CASE true WHEN epidb_results_weekly."Q1_4" THEN 1 ELSE 0 END) + CASE true WHEN epidb_results_weekly."Q1_6" THEN 1 ELSE 0 END) + CASE true WHEN epidb_results_weekly."Q1_5" THEN 1 ELSE 0 END) >= 2) AND ((((CASE true WHEN epidb_results_weekly."Q1_17" THEN 1 ELSE 0 END + CASE true WHEN epidb_results_weekly."Q1_15" THEN 1 ELSE 0 END) + CASE true WHEN epidb_results_weekly."Q1_16" THEN 1 ELSE 0 END) + CASE true WHEN epidb_results_weekly."Q1_18" THEN 1 ELSE 0 END) >= 2)) THEN 'COMMON-COLD-and-GASTROINTESTINAL'::text WHEN ((((CASE true WHEN epidb_results_weekly."Q1_3" THEN 1 ELSE 0 END + CASE true WHEN epidb_results_weekly."Q1_4" THEN 1 ELSE 0 END) + CASE true WHEN epidb_results_weekly."Q1_6" THEN 1 ELSE 0 END) + CASE true WHEN epidb_results_weekly."Q1_5" THEN 1 ELSE 0 END) >= 2) THEN 'COMMON-COLD'::text WHEN ((((CASE true WHEN epidb_results_weekly."Q1_17" THEN 1 ELSE 0 END + CASE true WHEN epidb_results_weekly."Q1_15" THEN 1 ELSE 0 END) + CASE true WHEN epidb_results_weekly."Q1_16" THEN 1 ELSE 0 END) + CASE true WHEN epidb_results_weekly."Q1_18" THEN 1 ELSE 0 END) >= 2) THEN 'GASTROINTESTINAL'::text ELSE 'NON-SPECIFIC-SYMPTOMS'::text END AS status FROM epidb_results_weekly;


ALTER TABLE public.epidb_health_status_notired OWNER TO seb;

DROP VIEW epidb_health_status_fever;
CREATE VIEW epidb_health_status_fever AS
SELECT epidb_results_weekly.id AS epidb_results_weekly_id, CASE true WHEN epidb_results_weekly."Q1_0" THEN 'NO-SYMPTOMS'::text WHEN ((((epidb_results_weekly."Q5" = 0) OR (epidb_results_weekly."Q6b" = 0)) AND (epidb_results_weekly."Q1_1") AND (((((((epidb_results_weekly."Q1_2") OR (epidb_results_weekly."Q6d" = 3)) OR (epidb_results_weekly."Q6d" = 4)) OR (epidb_results_weekly."Q6d" = 5)) OR epidb_results_weekly."Q1_11") OR epidb_results_weekly."Q1_8") OR epidb_results_weekly."Q1_9")) AND ((epidb_results_weekly."Q1_5" OR epidb_results_weekly."Q1_6") OR epidb_results_weekly."Q1_7")) THEN 'ILI'::text WHEN ((((((NOT epidb_results_weekly."Q1_1") AND (NOT epidb_results_weekly."Q1_2")) AND ((epidb_results_weekly."Q6d" = 0) OR (epidb_results_weekly."Q6d" IS NULL))) AND ((epidb_results_weekly."Q1_3" OR epidb_results_weekly."Q1_4") OR epidb_results_weekly."Q1_14")) AND (epidb_results_weekly."Q11" = 2)) AND ((((CASE true WHEN epidb_results_weekly."Q1_17" THEN 1 ELSE 0 END + CASE true WHEN epidb_results_weekly."Q1_15" THEN 1 ELSE 0 END) + CASE true WHEN epidb_results_weekly."Q1_16" THEN 1 ELSE 0 END) + CASE true WHEN epidb_results_weekly."Q1_18" THEN 1 ELSE 0 END) >= 2)) THEN 'ALLERGY-or-HAY-FEVER-and-GASTROINTESTINAL'::text WHEN (((((NOT epidb_results_weekly."Q1_1") AND (NOT epidb_results_weekly."Q1_2")) AND ((epidb_results_weekly."Q6d" = 0) OR (epidb_results_weekly."Q6d" IS NULL))) AND ((epidb_results_weekly."Q1_3" OR epidb_results_weekly."Q1_4") OR epidb_results_weekly."Q1_14")) AND (epidb_results_weekly."Q11" = 2)) THEN 'ALLERGY-or-HAY-FEVER'::text WHEN (((((CASE true WHEN epidb_results_weekly."Q1_3" THEN 1 ELSE 0 END + CASE true WHEN epidb_results_weekly."Q1_4" THEN 1 ELSE 0 END) + CASE true WHEN epidb_results_weekly."Q1_6" THEN 1 ELSE 0 END) + CASE true WHEN epidb_results_weekly."Q1_5" THEN 1 ELSE 0 END) >= 2) AND ((((CASE true WHEN epidb_results_weekly."Q1_17" THEN 1 ELSE 0 END + CASE true WHEN epidb_results_weekly."Q1_15" THEN 1 ELSE 0 END) + CASE true WHEN epidb_results_weekly."Q1_16" THEN 1 ELSE 0 END) + CASE true WHEN epidb_results_weekly."Q1_18" THEN 1 ELSE 0 END) >= 2)) THEN 'COMMON-COLD-and-GASTROINTESTINAL'::text WHEN ((((CASE true WHEN epidb_results_weekly."Q1_3" THEN 1 ELSE 0 END + CASE true WHEN epidb_results_weekly."Q1_4" THEN 1 ELSE 0 END) + CASE true WHEN epidb_results_weekly."Q1_6" THEN 1 ELSE 0 END) + CASE true WHEN epidb_results_weekly."Q1_5" THEN 1 ELSE 0 END) >= 2) THEN 'COMMON-COLD'::text WHEN ((((CASE true WHEN epidb_results_weekly."Q1_17" THEN 1 ELSE 0 END + CASE true WHEN epidb_results_weekly."Q1_15" THEN 1 ELSE 0 END) + CASE true WHEN epidb_results_weekly."Q1_16" THEN 1 ELSE 0 END) + CASE true WHEN epidb_results_weekly."Q1_18" THEN 1 ELSE 0 END) >= 2) THEN 'GASTROINTESTINAL'::text ELSE 'NON-SPECIFIC-SYMPTOMS'::text END AS status FROM epidb_results_weekly;


ALTER TABLE public.epidb_health_status_fever OWNER TO seb;
