##' Calculate incidence from flusurvey data
##'
##' This calculates incidence according to a given column in the supplied data.
##' @param data a data table, usually generated by \code{\link{merge_data}}
##' @param incidence.columns one or more columns which specificy incidence; default: "ili"
##' @param aggregation the timescale of aggregation, by default "week"
##' @param denominator what to use as denominator, active members or all reports in a week
##' @param min.N the minimum denominator, by default 1000
##' @param by one or more variables by which to group
##' @import data.table
##' @return a data.table with the incidence
##' @author seb
##' @export
get_incidence <- function(data, incidence.columns = "ili", aggregation = c("week", "day", "month", "year"), denominator = c("active.members", "reports"), min.N = 1000, by = NULL)
{
    aggregation <- match.arg(aggregation)
    denominator <- match.arg(denominator)

    dt <- copy(data)
    
    ## required date columns
    columns <- c("symptoms.start.date", "date", "min.date", "max.date")
    names(columns) <- columns

    ## create new date columns if aggregation is not by day
    if (aggregation != "day")
    {
        columns <- sub("date$", paste(aggregation, "date", sep = "."), columns)

        for (col_id in seq_along(columns))
        {
            if (aggregation == "week")
            {
                new_dates <-
                    dt[, get(names(columns)[col_id]) -
                         wday(get(names(columns)[col_id])) + 2]
            } else if (aggregation == "month")
            {
                ## First of the month
                new_dates <-
                    dt[, as.Date(paste(year(get(names(columns)[col_id])),
                                       month(get(names(columns)[col_id])),
                                       1, sep = "-"))]
            } else if (aggregation == "year")
            {
                ## First of the month
                new_dates <- dt[, as.Date(paste(year(get(names(columns)[col_id])),
                                                1, 1, sep = "-"))]
            }
            dt[, paste(columns[col_id]) := new_dates]
        }
    }

    id_column <- grep("_id$", colnames(dt), value = TRUE)

    ## calculate incidence based on symptom start date
    incidence <- list()
    for (incidence_column in incidence.columns)
    {
        id_incidence <- dt[get(incidence_column) == 1, list(bouts = .N),
                           by = c(columns[["symptoms.start.date"]], id_column, "season", by)]
        incidence[[incidence_column]] <-
            id_incidence[, list(new.cases = .N),
                         by = c(columns[["symptoms.start.date"]], "season", by)]
        incidence[[incidence_column]][, type := incidence_column]
    }
    incidence <- rbindlist(incidence)
    setnames(incidence, columns[["symptoms.start.date"]], aggregation)

    ## work out denominator of active members
    if (denominator == "active.members")
    {
        incidence[, N := apply(incidence, 1, function(x)
                    {
                        current.date <- x[[aggregation]]
                        id_active <- dt[get(columns[["min.date"]]) <= current.date &
                                        get(columns[["max.date"]]) >= current.date,
                                        list(reports = .N), by = c(id_column, by)]
                        id_active[, .N]
                    })]
    } else
    {
        id_reports <- dt[, list(reports = .N), by = c(columns[["date"]], id_column, by)]
        reports <- id_reports[, .N, by = c(columns[["date"]], by)]
        setnames(reports, columns[["date"]], aggregation)
        incidence <- merge(incidence, reports, by = c(aggregation, by))
    }

    incidence <- incidence[N > min.N]
    
    incidence[, incidence := new.cases / N]

    setkeyv(incidence, c("type", aggregation))

    return(incidence)
}
